//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Tickets.Model;
    
    public partial class ticketsEntities : DbContext
    {
        public ticketsEntities()
            : base("name=ticketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Event> EventSet { get; set; }
        public virtual DbSet<Session> SessionSet { get; set; }
        public virtual DbSet<Ticket> TicketSet { get; set; }
        public virtual DbSet<Transaction> TransactionSet { get; set; }
        public virtual DbSet<TicketSale> TicketSaleSet { get; set; }
    }
}
