//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaim = new HashSet<AspNetUserClaim>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[StringLength(256, ErrorMessage = "UserName has a maximum length of 256.")]
    	[Required(ErrorMessage = "UserName is required.")]
    	[DataMember(Name = "UserName", IsRequired = true)]
    	public string UserName { get; set; }
        
    	[StringLength(256, ErrorMessage = "Password has a maximum length of 256.")]
    	[Required(ErrorMessage = "Password is required.")]
    	[DataMember(Name = "Password", IsRequired = true)]
    	public string Password { get; set; }
        
    	[Required(ErrorMessage = "Updated is required.")]
    	[DataMember(Name = "Updated", IsRequired = true)]
    	public System.DateTime? Updated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "AspNetUserClaim")]
    	public virtual ICollection<AspNetUserClaim> AspNetUserClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "Transaction")]
    	public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
