//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class AspNetUserClaim
    {
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[Required(ErrorMessage = "UserId is required.")]
    	[DataMember(Name = "UserId", IsRequired = true)]
    	public int UserId { get; set; }
        
    	[DataMember(Name = "ClaimType")]
    	public string ClaimType { get; set; }
        
    	[DataMember(Name = "ClaimValue")]
    	public string ClaimValue { get; set; }
    
        [DataMember(Name = "AspNetUser")]
    	public virtual AspNetUser AspNetUser { get; set; }
    }
}
