//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Session = new HashSet<Session>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[Required(ErrorMessage = "Name is required.")]
    	[DataMember(Name = "Name", IsRequired = true)]
    	public string Name { get; set; }
        
    	[Required(ErrorMessage = "Description is required.")]
    	[DataMember(Name = "Description", IsRequired = true)]
    	public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "Session")]
    	public virtual ICollection<Session> Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "Ticket")]
    	public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
