//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class TicketSale
    {
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[Required(ErrorMessage = "SessionId is required.")]
    	[DataMember(Name = "SessionId", IsRequired = true)]
    	public int SessionId { get; set; }
        
    	[Required(ErrorMessage = "TicketId is required.")]
    	[DataMember(Name = "TicketId", IsRequired = true)]
    	public int TicketId { get; set; }
        
    	[Required(ErrorMessage = "TransactionId is required.")]
    	[DataMember(Name = "TransactionId", IsRequired = true)]
    	public int TransactionId { get; set; }
    
        [DataMember(Name = "Session")]
    	public virtual Session Session { get; set; }
        [DataMember(Name = "Ticket")]
    	public virtual Ticket Ticket { get; set; }
        [DataMember(Name = "Transaction")]
    	public virtual Transaction Transaction { get; set; }
    }
}
