//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    [DataContract]
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.TicketSale = new HashSet<TicketSale>();
        }
    
        
    	[Key()]
    	[DataMember(Name = "Id")]
    	public int Id { get; set; }
        
    	[Required(ErrorMessage = "UserId is required.")]
    	[DataMember(Name = "UserId", IsRequired = true)]
    	public int UserId { get; set; }
        
    	[Required(ErrorMessage = "TimeStamp is required.")]
    	[DataMember(Name = "TimeStamp", IsRequired = true)]
    	public System.DateTime? TimeStamp { get; set; }
    
        [DataMember(Name = "AspNetUser")]
    	public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Name = "TicketSale")]
    	public virtual ICollection<TicketSale> TicketSale { get; set; }
    }
}
